---
apiVersion: v1
kind: Pod
metadata:
  name: sheduler
  labels:
    app: minimaldask
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker
  labels:
    app: minimaldask
    tier: worker
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3