# Requirements
[dependencies]
kubernetes = "~12.0.1"
dask = "~2021.3.1"

[dev-dependencies]
black = { version = "^18.3-alpha.0", python = "^3.6" }
flake8 = { version = "^3.9.0"}

[tool.black]
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''